In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
plt.rc('font', family='Malgun Gothic')
plt.rcParams['axes.unicode_minus'] = False

In [2]:
df = pd.read_csv('../../data/VC/origin_anlysis_data.csv')
df

,주력제품 해외 시장점유율(퍼센트),주력제품 국내 시장점유율(퍼센트),매출구조비율(중소기업),매출구조비율(글로벌),총자산회전율,자기자본비율,부채비율,순이익률,등록보유(특허권),창업 당시 창업자 최종학력,창업 당시 목표시장,기업성장단계,해외수출 및 진출과정 애로사항,Exit
0,0.0,1.00,10.0,0.0,0.056,-9.113,-1197.317,-1739.260,2,3,1,2,2,0
1,0.0,1.00,100.0,0.0,182.613,27.306,266.224,3.063,5,4,1,4,8,0
2,0.0,10.00,10.0,0.0,47.157,67.238,48.726,8.065,15,2,1,4,4,0
3,5.0,30.00,30.0,30.0,55.927,24.734,304.309,-6.119,0,2,3,3,3,1
4,0.0,30.00,30.0,0.0,69.228,46.665,114.292,-11.386,0,2,3,3,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10781,0.0,0.01,100.0,0.0,78.543,34.503,189.827,-11.720,7,3,1,2,1,0
10782,0.0,15.00,20.0,0.0,603.905,38.300,161.096,2.822,1,3,3,3,2,0
10783,0.0,1.00,50.0,0.0,385.063,19.612,409.890,-0.801,0,3,1,2,5,1
10784,0.0,5.00,0.0,0.0,511.376,29.754,236.092,2.205,0,3,1,3,2,1
10785,0.0,15.00,60.0,0.0,385.063,19.612,409.890,-0.801,0,3,1,3,7,1

In [4]:
a = df[df['Exit']==0]

In [6]:
b = df[df['Exit']==1]

In [7]:
print(len(a))
print(len(b))

9628
1158

# 수치형 변수들

In [12]:
cat_df = df.iloc[:,0:9]
cat_df['Exit'] = df['Exit']

In [13]:
cat_df_a = cat_df[cat_df['Exit']==0]
cat_df_b = cat_df[cat_df['Exit']==1]

In [19]:
cat_a_desc = cat_df_a.describe()

cat_a_desc = pd.DataFrame(cat_a_desc)
cat_a_desc

,주력제품 해외 시장점유율(퍼센트),주력제품 국내 시장점유율(퍼센트),매출구조비율(중소기업),매출구조비율(글로벌),총자산회전율,자기자본비율,부채비율,순이익률,등록보유(특허권),Exit
count,9628.000000,9628.000000,9628.000000,9628.000000,9628.000000,9628.000000,9628.000000,9628.000000,9628.000000,9628.0
mean,0.828994,9.416934,38.503973,9.376821,134.570337,39.329786,255.338437,-10.655346,7.316369,0.0
std,4.657462,14.361033,37.881225,20.767284,131.064742,32.562173,935.430992,128.332992,18.460591,0.0
min,0.000000,0.000000,0.000000,0.000000,0.000000,-294.118000,-6045.455000,-1739.260000,0.000000,0.0
25%,0.000000,0.500000,0.000000,0.000000,69.979250,26.390500,70.090250,0.960750,1.000000,0.0
50%,0.000000,5.000000,30.000000,0.000000,106.797000,38.823000,147.285000,3.294000,3.000000,0.0
75%,0.010000,10.000000,70.000000,5.000000,161.580500,55.939500,257.419000,7.114750,8.000000,0.0
max,100.000000,100.000000,100.000000,100.000000,1868.724000,100.000000,12300.000000,175.477000,943.000000,0.0

In [21]:
cat_b_desc = cat_df_b.describe()

cat_b_desc = pd.DataFrame(cat_b_desc)
cat_b_desc

,주력제품 해외 시장점유율(퍼센트),주력제품 국내 시장점유율(퍼센트),매출구조비율(중소기업),매출구조비율(글로벌),총자산회전율,자기자본비율,부채비율,순이익률,등록보유(특허권),Exit
count,1158.000000,1158.000000,1158.000000,1158.000000,1158.000000,1158.000000,1158.000000,1158.000000,1158.000000,1158.0
mean,2.745596,14.100855,32.409344,17.575604,82.685602,57.539504,116.999756,-26.380313,17.735751,1.0
std,9.001737,17.447332,34.638759,26.910910,61.828602,27.425139,432.887921,163.852619,28.918135,0.0
min,0.000000,0.000000,0.000000,0.000000,0.229000,-294.118000,-6045.455000,-1739.260000,0.000000,1.0
25%,0.000000,3.000000,0.000000,0.000000,44.540750,42.445000,27.492750,-7.232250,2.000000,1.0
50%,0.010000,8.000000,20.000000,0.350000,67.353000,59.389000,64.097500,2.967000,8.000000,1.0
75%,1.000000,20.000000,60.000000,25.000000,104.641750,77.270750,130.376250,10.114500,21.000000,1.0
max,98.000000,100.000000,100.000000,100.000000,511.376000,98.929000,8096.269000,175.477000,413.000000,1.0

> 시장점유율(퍼센트)

In [23]:
market_share = pd.DataFrame(index=cat_b_desc.index)

market_share['주력제품 해외 시장점유율(퍼센트)_0'] = cat_a_desc['주력제품 해외 시장점유율(퍼센트)']
market_share['주력제품 해외 시장점유율(퍼센트)_1'] = cat_b_desc['주력제품 해외 시장점유율(퍼센트)']
market_share['주력제품 국내 시장점유율(퍼센트)_0'] = cat_a_desc['주력제품 국내 시장점유율(퍼센트)']
market_share['주력제품 국내 시장점유율(퍼센트)_1'] = cat_b_desc['주력제품 국내 시장점유율(퍼센트)']

market_share

,주력제품 해외 시장점유율(퍼센트)_0,주력제품 해외 시장점유율(퍼센트)_1,주력제품 국내 시장점유율(퍼센트)_0,주력제품 국내 시장점유율(퍼센트)_1
count,9628.000000,1158.000000,9628.000000,1158.000000
mean,0.828994,2.745596,9.416934,14.100855
std,4.657462,9.001737,14.361033,17.447332
min,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.500000,3.000000
50%,0.000000,0.010000,5.000000,8.000000
75%,0.010000,1.000000,10.000000,20.000000
max,100.000000,98.000000,100.000000,100.000000

> 매출구조비율

In [24]:
sales_struc = pd.DataFrame(index=cat_b_desc.index)

sales_struc['매출구조비율(중소기업)_0'] = cat_a_desc['매출구조비율(중소기업)']
sales_struc['매출구조비율(중소기업)_1'] = cat_b_desc['매출구조비율(중소기업)']
sales_struc['매출구조비율(글로벌)_0'] = cat_a_desc['매출구조비율(글로벌)']
sales_struc['매출구조비율(글로벌)_1'] = cat_b_desc['매출구조비율(글로벌)']

sales_struc

       매출구조비율(중소기업)_0  매출구조비율(중소기업)_1  매출구조비율(글로벌)_0  매출구조비율(글로벌)_1
count     9628.000000     1158.000000    9628.000000    1158.000000
mean        38.503973       32.409344       9.376821      17.575604
std         37.881225       34.638759      20.767284      26.910910
min          0.000000        0.000000       0.000000       0.000000
25%          0.000000        0.000000       0.000000       0.000000
50%         30.000000       20.000000       0.000000       0.350000
75%         70.000000       60.000000       5.000000      25.000000
max        100.000000      100.000000     100.000000     100.000000

> 재무비율

In [25]:
financial_rate = pd.DataFrame(index=cat_b_desc.index)

financial_rate['총자산회전율_0'] = cat_a_desc['총자산회전율']
financial_rate['총자산회전율_1'] = cat_b_desc['총자산회전율']
financial_rate['자기자본비율_0'] = cat_a_desc['자기자본비율']
financial_rate['자기자본비율_1'] = cat_b_desc['자기자본비율']
financial_rate['부채비율_0'] = cat_a_desc['부채비율']
financial_rate['부채비율_1'] = cat_b_desc['부채비율']
financial_rate['순이익률_0'] = cat_a_desc['순이익률']
financial_rate['순이익률_1'] = cat_b_desc['순이익률']

financial_rate

,총자산회전율_0,총자산회전율_1,자기자본비율_0,자기자본비율_1,부채비율_0,부채비율_1,순이익률_0,순이익률_1
count,9628.000000,1158.000000,9628.000000,1158.000000,9628.000000,1158.000000,9628.000000,1158.000000
mean,134.570337,82.685602,39.329786,57.539504,255.338437,116.999756,-10.655346,-26.380313
std,131.064742,61.828602,32.562173,27.425139,935.430992,432.887921,128.332992,163.852619
min,0.000000,0.229000,-294.118000,-294.118000,-6045.455000,-6045.455000,-1739.260000,-1739.260000
25%,69.979250,44.540750,26.390500,42.445000,70.090250,27.492750,0.960750,-7.232250
50%,106.797000,67.353000,38.823000,59.389000,147.285000,64.097500,3.294000,2.967000
75%,161.580500,104.641750,55.939500,77.270750,257.419000,130.376250,7.114750,10.114500
max,1868.724000,511.376000,100.000000,98.929000,12300.000000,8096.269000,175.477000,175.477000

> 특허권

In [26]:
patent = pd.DataFrame(index=cat_b_desc.index)

patent['등록보유(특허권)_0'] = cat_a_desc['등록보유(특허권)']
patent['등록보유(특허권)_1'] = cat_b_desc['등록보유(특허권)']

patent

       등록보유(특허권)_0  등록보유(특허권)_1
count  9628.000000  1158.000000
mean      7.316369    17.735751
std      18.460591    28.918135
min       0.000000     0.000000
25%       1.000000     2.000000
50%       3.000000     8.000000
75%       8.000000    21.000000
max     943.000000   413.000000