In [58]:
import pandas as pd

In [59]:
df2 = pd.read_csv('/Users/taewon/Documents/금융 빅데이터/project_1/trash/(완)data).csv')

In [3]:
df2.drop(columns=['회사주소_시(도)','한국표준산업분류(KSIC)코드_10차','상장여부','인수합병(MnA) 경험여부','가중치','벤처확인 유형'], inplace=True)

feature selection 전 data
- Min&Max Scailing X
- One Hot Encoding X

1. 범주형 변수

In [47]:
# 제품및서비스구조
b = df2[df2["벤처캐피털(투자조합포함) 투자 경험여부"]==1]
b["제품및서비스구조"].value_counts()

제품및서비스구조
3.0    391
2.0    379
1.0    147
Name: count, dtype: int64

In [48]:
b = df2[df2["벤처캐피털(투자조합포함) 투자 경험여부"]==0]
b["제품및서비스구조"].value_counts()

제품및서비스구조
2.0    5192
3.0    4296
1.0    1980
Name: count, dtype: int64

In [24]:
# 제조 및 비제조
b = df2[df2["벤처캐피털(투자조합포함) 투자 경험여부"]==1]
b["제조 및 비제조"].value_counts()

제조 및 비제조
1    334
4    272
2    269
3     42
Name: count, dtype: int64

In [25]:
b = df2[df2["벤처캐피털(투자조합포함) 투자 경험여부"]==0]
b["제조 및 비제조"].value_counts()

제조 및 비제조
2    4070
1    3943
4    2978
3     477
Name: count, dtype: int64

In [28]:
# 창업 당시 창업자 연령
b = df2[df2["벤처캐피털(투자조합포함) 투자 경험여부"]==1]
b["창업 당시 창업자 연령"].value_counts()

창업 당시 창업자 연령
2    375
3    355
4    131
1     32
5     24
Name: count, dtype: int64

In [29]:
b = df2[df2["벤처캐피털(투자조합포함) 투자 경험여부"]==0]
b["창업 당시 창업자 연령"].value_counts()

창업 당시 창업자 연령
3    4978
2    4210
4    1559
5     373
1     348
Name: count, dtype: int64

In [30]:
# 창업방식
b = df2[df2["벤처캐피털(투자조합포함) 투자 경험여부"]==1]
b["창업방식"].value_counts()

창업방식
3    797
2     62
1     58
Name: count, dtype: int64

In [31]:
b = df2[df2["벤처캐피털(투자조합포함) 투자 경험여부"]==0]
b["창업방식"].value_counts()

창업방식
3    10782
2      350
1      336
Name: count, dtype: int64

In [13]:
# 해외수출 및 진출과정 애로사항
b = df2[df2["벤처캐피털(투자조합포함) 투자 경험여부"]==1]
b["해외수출 및 진출과정 애로사항"].value_counts()

해외수출 및 진출과정 애로사항
3.0    201
2.0    174
4.0    174
7.0    125
5.0     98
1.0     63
8.0     45
6.0     37
Name: count, dtype: int64

In [14]:
b = df2[df2["벤처캐피털(투자조합포함) 투자 경험여부"]==0]
b["해외수출 및 진출과정 애로사항"].value_counts()

해외수출 및 진출과정 애로사항
3.0    2995
2.0    2332
4.0    1894
1.0    1442
5.0    1108
7.0     847
8.0     538
6.0     312
Name: count, dtype: int64

2. 비율 & 수치형 변수

In [60]:
df2 = df2[['주력제품 국내 시장점유율(퍼센트)',
 '주력제품 해외 시장점유율(퍼센트)',
 '정규직비율',
 '학력별 인력구성비(고졸이하)',
 '학력별 인력구성비(전문대졸)',
 '학력별 인력구성비(대졸)',
 '학력별 인력구성비(석사)',
 '학력별 인력구성비(박사)',
 '부서별_인력구성(관리)',
 '부서별_인력구성(생산)',
 '부서별_인력구성(영업)',
 '부서별_인력구성(RnD)',
 '부서별_인력구성(기타)',
 '매출구조비율(대기업)',
 '매출구조비율(12차벤더)',
 '매출구조비율(중소기업)',
 '매출구조비율(B2C)',
 '매출구조비율(B2G)',
 '매출구조비율(글로벌)',
 '투자액비(국내설비)',
 '투자액비(RnD)',
 '투자액비(해외)',
 '투자액비(기타)',
 '부채비율',
 '자기자본비율',
 '순이익률',
 '총자산회전율',
 '자기자본회전율',
 'ROE',
 '영업이익률',
 '이자보상배율',
 '종사자생산성',
 '창업 당시 창업자 실무경험 년수(년)',
 '벤처확인제도 혜택(평균)',
 '벤처인프라 수준(평균)',
 '등록보유(합계)',
 '출원중(합계)',
 '경영상 애로사항(개수)',
 '벤처캐피털(투자조합포함) 투자 경험여부']]

In [61]:
df2[df2["벤처캐피털(투자조합포함) 투자 경험여부"]==1].describe()

,주력제품 국내 시장점유율(퍼센트),주력제품 해외 시장점유율(퍼센트),정규직비율,학력별 인력구성비(고졸이하),학력별 인력구성비(전문대졸),학력별 인력구성비(대졸),학력별 인력구성비(석사),학력별 인력구성비(박사),부서별_인력구성(관리),부서별_인력구성(생산),...,영업이익률,이자보상배율,종사자생산성,창업 당시 창업자 실무경험 년수(년),벤처확인제도 혜택(평균),벤처인프라 수준(평균),등록보유(합계),출원중(합계),경영상 애로사항(개수),벤처캐피털(투자조합포함) 투자 경험여부
count,917.000000,917.000000,915.000000,917.000000,917.000000,917.000000,917.000000,917.000000,917.000000,917.000000,...,917.000000,917.000000,917.000000,917.000000,917.000000,917.000000,917.000000,917.000000,917.000000,917.0
mean,15.450218,2.863075,0.980191,17.091252,15.409438,54.359083,9.560358,3.579869,21.855068,27.111468,...,-63.514731,5736.466117,29221.692363,9.876009,3.520164,3.153217,16.748092,2.584515,5.471101,1.0
std,19.197304,8.046664,0.072356,19.335027,12.324227,23.405696,11.648341,7.525801,15.977665,24.427932,...,229.033904,33594.122802,39109.037656,7.373762,0.562211,0.558258,34.704064,9.392735,3.117860,0.0
min,0.000000,0.000000,0.135000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-1245.946000,-36650.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.0
25%,2.000000,0.000000,1.000000,0.000000,5.000000,37.500000,2.000000,0.000000,12.000000,1.316000,...,-18.634000,-785.455000,9834.343000,4.000000,3.167000,3.000000,1.000000,0.000000,3.000000,1.0
50%,8.000000,0.010000,1.000000,10.000000,14.000000,53.000000,6.000000,0.495050,17.857000,22.222000,...,2.300000,136.880000,19219.289000,10.000000,3.500000,3.000000,6.000000,0.000000,5.000000,1.0
75%,20.000000,1.000000,1.000000,29.000000,22.077922,71.000000,12.307692,4.000000,26.667000,48.718000,...,8.013000,740.909000,35891.150000,15.000000,3.833000,3.500000,20.000000,1.000000,7.000000,1.0
max,100.000000,80.000000,1.000000,92.000000,75.000000,100.000000,100.000000,81.395349,100.000000,96.296000,...,71.439000,147600.000000,420700.000000,35.000000,5.000000,5.000000,686.000000,164.000000,15.000000,1.0

In [62]:
df2[df2["벤처캐피털(투자조합포함) 투자 경험여부"]==0].describe()

,주력제품 국내 시장점유율(퍼센트),주력제품 해외 시장점유율(퍼센트),정규직비율,학력별 인력구성비(고졸이하),학력별 인력구성비(전문대졸),학력별 인력구성비(대졸),학력별 인력구성비(석사),학력별 인력구성비(박사),부서별_인력구성(관리),부서별_인력구성(생산),...,영업이익률,이자보상배율,종사자생산성,창업 당시 창업자 실무경험 년수(년),벤처확인제도 혜택(평균),벤처인프라 수준(평균),등록보유(합계),출원중(합계),경영상 애로사항(개수),벤처캐피털(투자조합포함) 투자 경험여부
count,11468.000000,11468.000000,11446.000000,11468.000000,11468.000000,11468.000000,11468.000000,11468.000000,11467.000000,11467.000000,...,11468.000000,11468.000000,11468.000000,11468.000000,11468.000000,11468.000000,11468.000000,11468.000000,11468.000000,11468.0
mean,10.478478,1.090296,0.987724,25.182434,18.936181,47.748649,6.543709,1.589026,19.400208,35.179606,...,-7.366754,6943.633066,31591.631932,10.435769,3.504359,3.121534,12.439048,1.602023,5.430415,0.0
std,15.555890,5.550095,0.063103,24.014220,14.207847,24.374866,10.332650,5.244736,13.530157,26.268099,...,94.755064,30054.955557,44605.068457,7.296109,0.535969,0.505005,30.342639,9.051925,2.920705,0.0
min,0.000000,0.000000,0.016000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-1245.946000,-36650.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.0
25%,1.000000,0.000000,1.000000,0.000000,10.000000,28.571429,0.000000,0.000000,11.111000,7.843000,...,1.347750,104.237500,11294.279500,5.000000,3.167000,2.750000,1.000000,0.000000,3.000000,0.0
50%,5.000000,0.000000,1.000000,20.000000,18.000000,44.444444,3.000000,0.000000,16.667000,37.500000,...,4.278500,322.727000,20006.034500,10.000000,3.500000,3.000000,4.000000,0.000000,5.000000,0.0
75%,10.000000,0.010000,1.000000,45.000000,26.315789,66.666667,9.000000,0.000000,24.074000,57.200500,...,8.379000,1104.069500,34921.622000,15.000000,3.833000,3.500000,12.250000,1.000000,7.000000,0.0
max,100.000000,100.000000,1.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,71.439000,147600.000000,420700.000000,50.000000,5.000000,5.000000,973.000000,279.000000,15.000000,0.0

In [65]:
a = df2[df2['벤처캐피털(투자조합포함) 투자 경험여부']==1]

In [68]:
b = df2[df2['벤처캐피털(투자조합포함) 투자 경험여부']==0]

In [67]:
a.sort_values('주력제품 국내 시장점유율(퍼센트)',ascending=False)[:30]

,주력제품 국내 시장점유율(퍼센트),주력제품 해외 시장점유율(퍼센트),정규직비율,학력별 인력구성비(고졸이하),학력별 인력구성비(전문대졸),학력별 인력구성비(대졸),학력별 인력구성비(석사),학력별 인력구성비(박사),부서별_인력구성(관리),부서별_인력구성(생산),...,영업이익률,이자보상배율,종사자생산성,창업 당시 창업자 실무경험 년수(년),벤처확인제도 혜택(평균),벤처인프라 수준(평균),등록보유(합계),출원중(합계),경영상 애로사항(개수),벤처캐피털(투자조합포함) 투자 경험여부
5233,100.0,50.00,1.000,0.000000,0.000000,50.000000,20.000000,30.000000,10.000,15.000,...,-225.086,-9780.000,4345.000,10.0,4.000,4.00,82,11,4,1
6825,100.0,30.00,1.000,69.400000,8.600000,19.600000,2.400000,0.000000,10.000,75.556,...,9.475,7533.103,64048.889,7.0,3.833,3.50,44,10,4,1
1267,90.0,40.00,1.000,33.000000,10.000000,45.000000,10.000000,2.000000,5.806,70.968,...,9.950,355.477,22727.097,10.0,3.667,2.50,25,1,7,1
2155,90.0,30.00,1.000,50.000000,15.000000,30.000000,5.000000,0.000000,16.556,78.808,...,-1.855,-35.547,31918.543,10.0,3.000,3.00,6,0,3,1
3104,90.0,5.00,1.000,71.000000,8.000000,20.000000,1.000000,0.000000,2.703,72.973,...,5.422,300.926,18731.250,17.0,4.000,3.50,4,0,8,1
3184,85.0,10.00,1.000,29.710145,27.536232,32.246377,7.608696,2.898551,15.217,35.145,...,5.832,517.317,51766.904,11.0,3.833,3.50,3,4,3,1
9755,80.0,0.00,0.950,0.000000,5.000000,82.000000,10.000000,3.000000,8.333,66.667,...,-149.940,-36650.000,5543.333,10.0,3.500,3.25,0,0,4,1
7240,80.0,3.00,1.000,30.769231,42.307692,19.230769,3.846154,3.846154,23.077,23.077,...,-31.770,-649.065,14103.226,11.0,3.333,3.00,34,1,6,1
11540,80.0,20.00,1.000,0.000000,7.894737,92.105263,0.000000,0.000000,7.895,0.000,...,8.299,2478.571,15485.185,8.0,4.167,3.25,0,0,3,1
1507,80.0,30.00,0.510,52.000000,12.000000,28.000000,0.000000,8.000000,4.390,61.951,...,16.639,3945.714,16063.871,14.0,3.667,4.00,19,5,3,1
4075,75.0,30.00,1.000,6.514658,12.052117,65.472313,14.332248,1.628664,12.378,3.583,...,19.287,1137.568,22336.082,17.0,4.000,4.00,0,0,0,1
1645,70.0,10.00,1.000,40.000000,6.666667,37.777778,13.333333,2.222222,24.444,35.556,...,2.006,185.000,83535.849,10.0,3.833,4.00,2,1,8,1
3780,70.0,10.00,1.000,29.000000,17.000000,42.000000,8.000000,4.000000,16.667,33.333,...,8.591,200.000,25025.000,10.0,2.000,2.00,13,7,9,1
9912,70.0,0.00,0.978,0.000000,12.000000,86.000000,2.000000,0.000000,80.435,10.870,...,5.292,548.000,11256.522,7.0,3.333,3.25,8,0,6,1
7029,70.0,0.00,1.000,42.000000,22.000000,34.000000,2.000000,0.000000,18.000,62.000,...,-0.914,-95.286,30976.000,9.0,4.000,3.25,2,0,4,1
2252,70.0,3.00,0.957,60.000000,2.000000,38.000000,0.000000,0.000000,17.021,61.702,...,0.737,167.614,85127.660,19.0,3.500,3.00,1,0,7,1
4375,70.0,0.01,1.000,25.000000,25.000000,30.000000,20.000000,0.000000,13.636,27.273,...,4.491,237.349,19940.909,23.0,4.500,2.75,16,3,1,1
4532,70.0,20.00,1.000,0.000000,0.000000,0.000000,50.000000,50.000000,0.000,0.000,...,3.533,287.500,32550.000,25.0,5.000,4.00,3,0,12,1
3168,70.0,0.00,1.000,32.989691,19.587629,40.206186,4.123711,3.092784,19.588,36.598,...,12.865,26908.333,75674.372,22.0,4.167,4.00,1,0,3,1
6290,70.0,2.00,1.000,49.500000,25.000000,24.000000,1.500000,0.000000,27.000,63.000,...,8.590,199.794,28282.000,10.0,3.833,2.75,58,0,3,1
6517,70.0,15.00,1.000,15.584416,22.077922,52.597403,5.844156,3.896104,8.442,55.844,...,4.697,30764.706,38394.483,18.0,3.500,3.25,204,0,6,1
6623,70.0,0.00,1.000,11.000000,6.000000,81.000000,2.000000,0.000000,11.111,1.667,...,8.286,541.506,35688.333,10.0,3.333,3.50,49,0,9,1
7188,70.0,50.00,1.000,25.000000,30.000000,40.000000,5.000000,0.000000,31.250,38.542,...,4.173,320.538,32726.042,10.0,3.667,4.00,114,0,9,1
1259,70.0,0.00,1.000,44.000000,31.000000,25.000000,0.000000,0.000000,12.500,78.125,...,12.434,135.885,7137.500,10.0,3.167,3.00,116,1,7,1
10678,70.0,0.01,1.000,4.000000,4.000000,71.000000,21.000000,0.000000,83.193,0.000,...,8.926,4087.251,96582.353,26.0,5.000,4.50,46,4,9,1
6967,70.0,60.00,1.000,5.000000,75.000000,15.000000,5.000000,0.000000,17.222,43.889,...,-13.705,-442.163,18822.727,5.0,3.333,2.25,250,20,9,1
11304,70.0,0.00,1.000,14.007782,18.677043,52.140078,9.727626,5.447471,18.677,0.000,...,-2.111,-85.360,8669.149,8.0,3.833,2.75,0,0,7,1
12237,70.0,0.00,1.000,10.000000,50.000000,40.000000,0.000000,0.000000,5.208,40.625,...,8.199,285.615,22583.146,2.0,4.000,3.00,2,0,3,1
2747,70.0,0.50,0.958,61.000000,4.000000,35.000000,0.000000,0.000000,19.718,54.930,...,4.149,88.728,20555.556,32.0,2.000,3.00,8,0,0,1
11466,70.0,0.00,1.000,6.666667,45.333333,33.333333,10.666667,4.000000,9.333,0.000,...,-57.288,-921.681,5426.866,5.0,4.667,4.75,3,0,7,1

In [69]:
b.sort_values('주력제품 국내 시장점유율(퍼센트)',ascending=False)[:30]

,주력제품 국내 시장점유율(퍼센트),주력제품 해외 시장점유율(퍼센트),정규직비율,학력별 인력구성비(고졸이하),학력별 인력구성비(전문대졸),학력별 인력구성비(대졸),학력별 인력구성비(석사),학력별 인력구성비(박사),부서별_인력구성(관리),부서별_인력구성(생산),...,영업이익률,이자보상배율,종사자생산성,창업 당시 창업자 실무경험 년수(년),벤처확인제도 혜택(평균),벤처인프라 수준(평균),등록보유(합계),출원중(합계),경영상 애로사항(개수),벤처캐피털(투자조합포함) 투자 경험여부
2480,100.00,30.00,0.950,50.0,20.0,20.0,10.0,0.0,6.429,32.857,...,10.852,3125.439,23452.143,0.0,5.000,4.50,13,0,7,0
3751,100.00,0.00,1.000,10.0,10.0,80.0,0.0,0.0,4.412,13.235,...,2.249,108.897,16198.810,0.0,3.000,3.00,29,0,7,0
977,100.00,0.00,1.000,0.0,20.0,20.0,20.0,40.0,20.000,20.000,...,-61.888,-3540.000,5720.000,15.0,3.333,2.75,0,2,7,0
3263,100.00,0.00,1.000,14.0,14.0,29.0,29.0,14.0,14.286,28.571,...,6.502,5800.000,12742.857,10.0,2.833,2.00,0,0,8,0
6102,100.00,1.00,0.971,32.0,12.0,56.0,0.0,0.0,20.588,35.294,...,5.746,474.286,33985.294,13.0,3.000,3.00,0,0,7,0
7092,100.00,0.00,1.000,90.0,10.0,0.0,0.0,0.0,11.111,44.444,...,8.314,963.636,15937.500,28.0,3.833,3.00,0,0,5,0
2177,100.00,0.00,1.000,59.0,31.0,9.0,1.0,0.0,9.877,90.123,...,-1.591,-172.139,13422.222,30.0,3.000,3.00,0,0,4,0
10152,100.00,0.00,1.000,6.6,20.0,60.2,6.6,6.6,22.222,44.444,...,-66.400,-11066.667,4166.667,9.0,4.500,4.25,21,0,0,0
7531,100.00,0.00,1.000,83.0,11.0,3.0,3.0,0.0,33.333,53.333,...,8.990,85.338,8416.667,11.0,2.833,2.75,20,0,8,0
7731,100.00,0.00,1.000,45.0,20.0,34.0,1.0,0.0,3.429,93.143,...,2.144,80.417,4286.190,30.0,4.000,3.00,0,0,4,0
2516,100.00,1.00,1.000,24.0,24.0,31.0,16.0,5.0,30.159,36.508,...,7.568,461.009,21077.778,25.0,4.000,3.00,4,1,1,0
1278,100.00,70.00,1.000,7.0,7.0,57.0,29.0,0.0,21.429,14.286,...,3.507,322.222,17721.429,5.0,4.000,4.00,0,2,15,0
4811,100.00,0.00,1.000,10.0,0.0,30.0,60.0,0.0,14.286,28.571,...,-0.339,-20.000,8428.571,12.0,4.333,3.25,7,0,5,0
5381,100.00,0.00,1.000,17.0,23.0,48.0,11.0,1.0,10.526,50.000,...,-3.877,-1493.396,21488.421,12.0,3.333,3.50,27,0,1,0
3840,100.00,0.00,1.000,6.0,25.0,44.0,25.0,0.0,56.250,25.000,...,4.886,217.647,18931.250,10.0,3.000,2.00,12,5,0,0
4957,100.00,60.00,1.000,8.0,12.0,57.0,20.0,3.0,13.725,29.412,...,5.118,605.263,26435.294,10.0,2.500,2.00,33,11,10,0
1499,100.00,0.00,1.000,50.0,0.0,50.0,0.0,0.0,25.000,50.000,...,10.655,138.318,17362.500,11.0,3.667,3.75,68,2,7,0
12070,100.00,2.00,1.000,5.0,10.0,85.0,0.0,0.0,48.718,15.385,...,12.441,1353.191,13107.692,8.0,3.667,3.00,0,0,4,0
7427,100.00,0.00,0.891,46.0,43.0,11.0,0.0,0.0,8.696,84.783,...,1.057,368.333,22734.783,22.0,3.333,3.00,15,0,3,0
4863,100.00,1.00,1.000,17.0,33.0,33.0,17.0,0.0,33.333,33.333,...,4.487,339.286,35283.333,15.0,1.000,3.00,116,20,15,0
5181,98.11,0.00,1.000,25.0,23.0,48.0,4.0,0.0,31.579,42.105,...,4.706,147600.000,20398.182,11.0,3.000,2.25,12,4,4,0
794,98.00,98.00,1.000,2.0,23.0,61.0,8.0,6.0,17.829,48.062,...,26.036,6207.109,77990.698,10.0,3.500,3.00,0,3,4,0
6276,98.00,2.00,1.000,68.0,23.0,9.0,0.0,0.0,20.833,66.667,...,5.797,256.296,25952.174,3.0,3.167,2.00,0,0,10,0
6803,95.00,0.60,1.000,67.0,20.0,7.0,3.0,3.0,9.722,65.278,...,4.775,712.745,23789.062,10.0,3.333,3.75,12,1,3,0
4470,95.00,0.00,0.875,0.0,50.0,33.0,0.0,17.0,28.571,42.857,...,-39.565,-379.167,5750.000,15.0,4.000,3.00,2,0,4,0
3259,95.00,1.00,1.000,20.0,30.0,50.0,0.0,0.0,18.750,12.500,...,-32.469,-808.065,9643.750,18.0,3.000,3.50,6,0,3,0
587,95.00,5.00,1.000,0.0,0.0,90.0,10.0,0.0,2.817,5.634,...,13.835,147600.000,23141.270,0.0,4.000,3.00,112,0,1,0
4527,92.00,10.00,1.000,42.0,33.0,25.0,0.0,0.0,25.000,41.667,...,4.044,486.667,15041.667,0.0,3.333,3.00,21,0,6,0
3064,92.00,8.00,1.000,34.0,29.0,37.0,0.0,0.0,10.417,41.667,...,20.440,2804.762,19211.111,11.0,3.333,3.00,7,1,2,0
9198,92.00,0.01,1.000,0.0,3.5,95.0,1.5,0.0,9.167,4.167,...,15.215,5907.101,18226.111,8.0,4.833,3.00,20,0,0,0